package com.redhat.fsi.creditcarddisputecase;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AdditionalInformation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer questionId;
	private java.lang.String answerValue;
	private java.lang.String questionType;
	private java.lang.String questionPrompt;

	public AdditionalInformation() {
	}

	public java.lang.Integer getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(java.lang.Integer questionId) {
		this.questionId = questionId;
	}

	public java.lang.String getAnswerValue() {
		return this.answerValue;
	}

	public void setAnswerValue(java.lang.String answerValue) {
		this.answerValue = answerValue;
	}

	public java.lang.String getQuestionType() {
		return this.questionType;
	}

	public void setQuestionType(java.lang.String questionType) {
		this.questionType = questionType;
	}

	public java.lang.String getQuestionPrompt() {
		return this.questionPrompt;
	}

	public void setQuestionPrompt(java.lang.String questionPrompt) {
		this.questionPrompt = questionPrompt;
	}

	public AdditionalInformation(java.lang.Integer questionId,
			java.lang.String answerValue, java.lang.String questionType,
			java.lang.String questionPrompt) {
		this.questionId = questionId;
		this.answerValue = answerValue;
		this.questionType = questionType;
		this.questionPrompt = questionPrompt;
	}

}
