package com.redhat.fsi.creditcarddisputecase;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Cardholder implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String stateCode;
	private java.lang.Integer age;
	private java.lang.String status;
	private java.lang.Integer incidentCount;
	private java.lang.Float balanceRatio;
	private java.lang.Integer riskRating;

	public Cardholder() {
	}

	public java.lang.String getStateCode() {
		return this.stateCode;
	}

	public void setStateCode(java.lang.String stateCode) {
		this.stateCode = stateCode;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.Integer getIncidentCount() {
		return this.incidentCount;
	}

	public void setIncidentCount(java.lang.Integer incidentCount) {
		this.incidentCount = incidentCount;
	}

	public java.lang.Float getBalanceRatio() {
		return this.balanceRatio;
	}

	public void setBalanceRatio(java.lang.Float balanceRatio) {
		this.balanceRatio = balanceRatio;
	}

	public java.lang.Integer getRiskRating() {
		return this.riskRating;
	}

	public void setRiskRating(java.lang.Integer riskRating) {
		this.riskRating = riskRating;
	}

	public Cardholder(java.lang.String stateCode, java.lang.Integer age,
			java.lang.String status, java.lang.Integer incidentCount,
			java.lang.Float balanceRatio, java.lang.Integer riskRating) {
		this.stateCode = stateCode;
		this.age = age;
		this.status = status;
		this.incidentCount = incidentCount;
		this.balanceRatio = balanceRatio;
		this.riskRating = riskRating;
	}

	@Override
	public String toString() {
		return "Cardholder [stateCode=" + stateCode + ", age=" + age + ", status=" + status + ", incidentCount="
				+ incidentCount + ", balanceRatio=" + balanceRatio + ", riskRating=" + riskRating + "]";
	}

}
