package com.redhat.fsi.creditcarddisputecase;
import org.jbpm.casemgmt.api.model.instance.*;

rule "Manager Approval Required"
ruleflow-group "manager-approval-check"
dialect "mvel"
when
    $caseData : CaseFileInstance()
    FraudData(totalFraudAmount > 1000)
then
    Map<String, Object> params = new Map<>();
    params.put("caseFile_managerApprovalRequired", true);
    $caseData.addAll(params);
end

    